GameStore/Controllers/HomeController.cs
using GameStore.Data.Interfaces;
using GameStore.Data.Models;
using GameStore.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace GameStore.Controllers
{
    public class HomeController : Controller
    { 
        private readonly IAllGames _allGames;
        private readonly IGamesCategory _gamesCategory;
        public HomeController(IAllGames iAllGames, IGamesCategory iGamesCategory)
        {
            _allGames = iAllGames;
            _gamesCategory = iGamesCategory;
        }

        public IActionResult Index()
        {
            GamesListViewModel obj = new GamesListViewModel();
            obj.allGames = _allGames.Games;
            obj.gameCategory = "Games";
            return View(obj);
        }

        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GameStore/Controllers/ShopCartController.cs
using GameStore.Data.Interfaces;
using GameStore.Data.Models;
using GameStore.Data.Repository;
using GameStore.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameStore.Controllers
{
    public class ShopCartController : Controller
    {
        private IAllGames _gameRepository;
        private  ShopCart _shopCart;

        public ShopCartController(IAllGames gameRepository, ShopCart shopCart)
        {
            _shopCart = shopCart;
            _gameRepository = gameRepository;
        }
        public IActionResult Index()
        {
            var items = _shopCart.GetShopItems();
            _shopCart.listShopItems = items;

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };
            return View(obj);
        }

        public RedirectToActionResult addToCart (int id)
        {
            var item = _gameRepository.Games.FirstOrDefault(i => i.Id == id);
            if (item != null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }
    }
}

GameStore/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<h1>About</h1>

GameStore/Views/Home/Index.cshtml
@using GameStore.ViewModels
@using System.Globalization
@model GamesListViewModel
@{
    ViewData["Title"] = "Home Page";
}

<body>
    <h1>All games</h1>
    <h3>@Model.gameCategory</h3>
    <div class="container mb-4 mt-3">
        <div class="row">
            @{
                foreach (var game in Model.allGames)
                {
                    <div class="col-sm-4">
                        <img class="img-thumbnail" src="@game.Image" alt="@game.Name" width="240" height="320" />
                        <h2>@game.Name</h2>
                        <p>@game.ShortDescription</p>
                        <p>Price: @game.Price.ToString("c", CultureInfo.CreateSpecificCulture("en-US"))</p>
                        <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@game.Id">Buy</a></p>
                    </div>
                }
            }
        </div>
    </div>

</body>